file_types:
- .jpeg
- .mov
- .bmp
- .jpg
- .mp4
- .avi
- .heic
- .m4v
- .3gp
- .3g2
- .webp
- .tiff
- .tif
- .dng
skip_folders:
- '*:\Windows'
- '*:\Program Files*'
- '*:\ProgramData'
- '*:\$Recycle.Bin'
- '*:\System Volume Information'
- '*:\Recovery'
- '*:\PerfLogs'
- '*:\Apps'
- '*:\Users\*\AppData'
- '*\node_modules'
- '*\.git'
- '*\.svn'
- '*\.hg'
- '*\__pycache__'
- '*\.vscode'
- '*\.idea'
- '*\temp'
- '*\tmp'
- '*\cache'
- '*\logs'
- '*\images'
- '*\pkgs'
- '*\envs'
- '*\.conda'
- '*\Lib'
- '*\.nuget'
- '*\packages'
